name: Launch DO Testnet
on: 
  workflow_dispatch:
    inputs:
      launch:
        description: 'Set to non-empty if a new network should be launched'
        required: false
        default: ''
      client-tests:
        description: 'Set to non-empty if the clients tests should be run'
        required: false
        default: ''
      kill:
        description: 'Set to non-empty if the network should be killed'
        required: false
        default: ''
jobs:
  launch-testnet:
    if: github.events.inputs.launch != ''
    runs-on: ubuntu-latest
    steps:
      - run: echo "Launching..."
  run-client-tests:
    if: github.events.inputs.client-tests != ''
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running client tests...."
  kill-testnet:
    if: github.events.inputs.kill != ''
    runs-on: ubuntu-latest
    steps:
      - run: echo "Killing testnet..."
