name: Launch DO Testnet
on: create

jobs:
  kill-testnet:
    if: github.event.ref_type == 'branch' && startsWith(github.event.ref, 'testnet')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Branch ${{ github.event.ref }} was created"
