name: Triggered on request
on:
  pull_request_review:
    types: [submitted, edited]

jobs:
  run-testnet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event.review) }}"
      - run: echo "${{ toJson(github.event.review.body) }}"
      - run: echo "${{ github.event.review.body }}"
