name: Triggered on request
on:
  pull_request_review:
    types: [submitted, edited]

jobs:
  run-testnet:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJson(github.event) }}
      - run: echo ${{ toJson(github.event.pull_request) }}
      - run: echo ${{ toJson(github.event.pull_request.review) }}
