name: Triggered on request
on:
  pull_request_review:
    types: [submitted, edited]

jobs:
  run-testnet:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.review.body == 'launch-testnet'
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'testnet-${{ github.sha }}'
